repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -  id: flake8
       additional_dependencies: [
        'astroid==2.12.14',
        'pylint==2.15.10',
        'flake8-bugbear>=22.10.27',
        'flake8-comprehensions>=3.10',
        'flake8-debugger',
        'flake8-docstrings>=1.6.0',
        'flake8-isort>=5.0',
        'flake8-pylint',
        'flake8-rst-docstrings',
        'flake8-string-format'
       ]
